Examples:
- 'examples/**'

Library:
- 'lib/**'

ReadMe:
- 'readme.md'

CodeEditor:
- '.vscode/**'

Tests:
- any: ['test/**', '**/*.test.ts', '**/*.test.js']

Core:
- 'lib/core/**'

CoreWithTests:
- all: ['lib/core/**', 'test/**']

Actions:
- '.github/**'

Docs:
- 'Docs/**'

Types:
- 'lib/types/**'
