Examples:
  - any: ["examples/**"]

Library:
  - all: ["lib/**"]

ReadMe:
  - all: ["readme.md"]

CodeEditor:
  - all: [".vscode/**"]

Tests:
  - any: ["test/**", "**/*.test.ts", "**/*.test.js"]

Core:
  - all: ["lib/core/**"]

CoreWithTests:
  - all: ["lib/core/**", "test/**"]

Actions:
  - all: [".github/**"]

Docs:
  - all: ["Docs/**"]

Types:
  - all: ["lib/types/**"]

Packages:
  - all: ["**/**/package*.json"]

Codeowners:
  - all: [".github/CODEOWNERS"]
